### ISSUE TITLE
Connection Metrics

### ISSUE THREAD

**Issue by petenicholls** [IBMStreams/streamsx.rabbitmq#18]
The code resets the reconnection attempts metric every time there is a successful connection.  This leads to misleading stats about how often there are reconnections occurring in long running operators.

There should be either a new metric that collects all attempts, or repurpose the old one.

**Comment by schulz2** [comment]
Included in v1.2.0 release: https://github.com/IBMStreams/streamsx.rabbitmq/releases/tag/v1.2.0

**Comment by schulz2** [comment]
Mail by Pete says I may close the issue.
