### ISSUE TITLE
isConnected true....Rabbit server says otherwise

### ISSUE THREAD

**Issue by petenicholls** [IBMStreams/streamsx.rabbitmq#19]
Had a case where the source operator indicated it was connected and all was well but no tuples flowing.  Checking the server indicated that there was no client connection for this.

Not clear looking at the code that the isConnected is being handled correctly if there are exceptions.  Some cases do not set isConnected to false in the exception handlers.

**Comment by schulz2** [comment]
Included in v1.2.0 release: https://github.com/IBMStreams/streamsx.rabbitmq/releases/tag/v1.2.0

**Comment by schulz2** [comment]
Mail by Pete says I may close the issue.
