### ISSUE TITLE
Operators should use Java annotations

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.rabbitmq#7]
Currently, the RabbitMQ operators are defined in the toolkit.xml. The operators should instead be defined using the Java Operator Annotations (https://www.ibm.com/support/knowledgecenter/SSCRJU_4.2.1/com.ibm.streams.spl-java-operators.doc/api/com/ibm/streams/operator/model/package-summary.html).

**Comment by markheger** [comment]
a) toolkit.xml is generated and not part of the repository
b) Operator configuration is defined by annotations: 
e.g.
https://github.com/IBMStreams/streamsx.rabbitmq/blob/master/com.ibm.streamsx.rabbitmq/impl/java/src/com/ibm/streamsx/rabbitmq/RabbitMQSource.java

```
@OutputPorts(@OutputPortSet(cardinality = 1, optional = false, description = "Messages received are sent on this output port."))
@PrimitiveOperator(name = "RabbitMQSource", description = RabbitMQSource.DESC)
public class RabbitMQSource extends RabbitMQBaseOper {
```

**Comment by cancilla** [comment]
Ah, you are correct. I was running `ant` from the toolkit directory expecting it to index the toolkit but it doesn't. Instead, `ant` needs to be run from the repository directory in order for the toolkit to be indexed. 

I think the build.xml in the toolkit directory should also index the toolkit in addition to building the JAR file.
