### ISSUE TITLE
Proposal: Add SSL support to RabbitMQ operators

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.rabbitmq#8]
# Use Case

RabbitMQ supports creating secured channels via SSL. This functionality would allow Streams applications to send and receive data over an encrypted channel. This functionality is critically important for applications that are dealing with sensitive or private data. 

# Proposal 

I would like to propose that the RabbitMQ operators (RabbitMQSource and RabbitMQSink) be updated to support creating SSL connections. In order to support this functionality, the following changes need to be made to the operators: 

 * Operator parameters need to be added to allow the user to specify SSL specific settings, such as the keyStore and trustStore paths
 * The underlying operator code needs to be modified to support both unsecured and secured (via SSL) connections

## Parameters
The following are the list of parameters that should be added to the operator in order to support SSL: 

| Parameter Name | SPL Type | Default | Description |
| --- | --- | --- | --- |
| useSSL | `boolean` | false | Specifies whether an SSL connection should be created. If not specified, the default value is `false`. |
| sslProtocol | `rstring` | TLSv1.2 | Specifies the SSL protocol to use. If not specified, the default value is `TLSv1.2`. |
| keyStorePath | `rstring` | | Specifies the path to the keystore file. This parameter is required if the **useSSL** parameter is set to `true`. |
| keyStorePassword | `rstring` | | Specifies the password used to unlock the keystore. This parameter is required if the **useSSL** parameter is set to `true`. |
| keyStoreAlgorithm | `rstring` | IbmX509 | Specifies the algorithm that was used to encrypt the keystore. If not specified, the operator will use the JVM's default algorithm (typically `IbmX509`). |
| keyStoreType | `rstring` | JKS | Specifies the keystore type. If not specified, the operator will use the JVM's default type (typically `JKS`). |
| trustStorePath | `rstring` | | Specifies the path to the trustStore file. This parameter is required if the **useSSL** parameter is set to `true`. |
| trustStorePassword | `rstring` | | Specifies the password used to unlock the trustStore. |
| trustStoreAlgorithm | `rstring` | IbmX509 | Specifies the algorithm that was used to encrypt the trustStore. If not specified, the operator will use the JVM's default algorithm (typically `IbmX509`). |
| trustStoreType | `rstring` | JKS | Specifies the trustStore type. If not specified, the operator will use the JVM's default type (typically `JKS`). |

## Code Modification
A pull request will be opened containing the changes proposed in this issue. 

## Compatibility
The proposed changes will **NOT** break compatibility with existing applications.

**Comment by schulz2** [comment]
+1
